services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./stress_history.db:/app/stress_history.db
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
